name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stopping old docker container
      run: sudo docker stop /myapp || true
    - name: Removing old docker container
      run: sudo docker rm /myapp || true
    - name: Build docker images
      run: sudo docker build -t learn-docker:1.0.0 .
    - name: Run docker
      run: sudo docker run -itd -p 1323:1323 --name myapp learn-docker:1.0.0